#!/bin/bash
S=100
V=10
U=4
A=10
T=4
P=0

# S=10000
# V=1000
# U=4
# A=100
# T=16
# P=0

echo "javac Dataflow.java && java -Xmx2048M Dataflow $S $V $U $A $T $P"
javac Dataflow.java && java -Xmx2048M Dataflow $S $V $U $A $T $P
