#!/bin/bash
S=1000
V=100
U=4
A=10
T=4
P=0

# S=10000
# V=1000
# U=4
# A=100
# T=16
# P=0

echo "javac Seq.java && java -Xmx2048M Seq $S $V $U $A $T $P"
javac Seq.java && java -Xmx2048M Seq $S $V $U $A $T $P
